export const TYPE_COLORS = {
  Normal:'#9a9a7a',Fire:'#e07030',Water:'#5880e0',Electric:'#e8c020',
  Grass:'#68b840',Ice:'#88c8c8',Fighting:'#b02020',Poison:'#903090',
  Ground:'#d0b050',Flying:'#9878e0',Psychic:'#e04878',Bug:'#98a810',
  Rock:'#a89028',Ghost:'#604878',Dragon:'#6028e8',Dark:'#604838',
  Steel:'#a8a8c0',Fairy:'#de89ac',
};

export const MOVE_TYPES = {
  'Protect':'Normal','Fake Out':'Normal','Last Respects':'Ghost','Hyper Voice':'Normal',
  'Quick Attack':'Normal','Double-Edge':'Normal','Body Slam':'Normal','Feint':'Normal',
  'Super Fang':'Normal','Follow Me':'Normal','Wide Guard':'Rock','Heal Pulse':'Psychic',
  'Helping Hand':'Normal','Boomburst':'Normal','Substitute':'Normal','Disable':'Normal',
  'Encore':'Normal','Detect':'Fighting','Taunt':'Dark','Coaching':'Fighting',
  'Flare Blitz':'Fire','Heat Wave':'Fire','Overheat':'Fire','Fire Blast':'Fire',
  'Eruption':'Fire','Weather Ball':'Normal','Will-O-Wisp':'Fire','Mystical Fire':'Fire',
  'Flamethrower':'Fire','Sacred Fire':'Fire',
  'Aqua Jet':'Water','Wave Crash':'Water','Flip Turn':'Water','Waterfall':'Water',
  'Hydro Pump':'Water','Surf':'Water','Water Spout':'Water','Scald':'Water',
  'Muddy Water':'Water','Liquidation':'Water','Life Dew':'Water','Muddy Water':'Water',
  'Thunderbolt':'Electric','Thunder':'Electric','Volt Switch':'Electric','Electroweb':'Electric',
  'Discharge':'Electric','Wild Charge':'Electric','Electro Shot':'Electric','Thunderbolt':'Electric',
  'Leaf Blade':'Grass','Flower Trick':'Grass','Solar Beam':'Grass','Giga Drain':'Grass',
  'Spore':'Grass','Sleep Powder':'Grass','Leech Seed':'Grass','Matcha Gotcha':'Grass',
  'Rage Powder':'Bug','Pollen Puff':'Bug','U-turn':'Bug','X-Scissor':'Bug',
  'Blizzard':'Ice','Ice Shard':'Ice','Icicle Crash':'Ice','Freeze-Dry':'Ice',
  'Triple Axel':'Ice','Ice Beam':'Ice','Aurora Veil':'Ice','Icy Wind':'Ice',
  "Close Combat":'Fighting','High Jump Kick':'Fighting','Drain Punch':'Fighting',
  'Mach Punch':'Fighting','Low Kick':'Fighting','Sacred Sword':'Fighting',
  'Aura Sphere':'Fighting','Body Press':'Fighting','Brick Break':'Fighting',
  'Sludge Bomb':'Poison','Sludge Wave':'Poison','Poison Jab':'Poison',
  'Dire Claw':'Poison','Toxic':'Poison','Baneful Bunker':'Poison',
  'Earthquake':'Ground','Earth Power':'Ground','Stomping Tantrum':'Ground',
  'Headlong Rush':'Ground','High Horsepower':'Ground','Bone Rush':'Ground',
  'Brave Bird':'Flying','Acrobatics':'Flying','Air Slash':'Flying','Hurricane':'Flying',
  'Tailwind':'Flying','Quick Guard':'Flying','Dual Wingbeat':'Flying','Roost':'Flying',
  'Psychic':'Psychic','Psyshock':'Psychic','Expanding Force':'Psychic','Trick Room':'Psychic',
  'Twin Beam':'Psychic','Psycho Cut':'Psychic','Zen Headbutt':'Psychic',
  'Shadow Ball':'Ghost','Shadow Sneak':'Ghost','Phantom Force':'Ghost','Poltergeist':'Ghost',
  'Bitter Malice':'Ghost','Hex':'Ghost','Shadow Claw':'Ghost','Misty Explosion':'Ghost',
  "King's Shield":'Steel',
  'Dragon Claw':'Dragon','Dragon Pulse':'Dragon','Draco Meteor':'Dragon','Outrage':'Dragon',
  'Dragon Darts':'Dragon','Scale Shot':'Dragon','Dragon Rush':'Dragon','Clanging Scales':'Dragon',
  'Clangorous Soul':'Dragon','Dragon Dance':'Dragon',
  'Knock Off':'Dark','Crunch':'Dark','Sucker Punch':'Dark','Kowtow Cleave':'Dark',
  'Parting Shot':'Dark','Darkest Lariat':'Dark','Dark Pulse':'Dark','Foul Play':'Dark',
  'Throat Chop':'Dark',
  'Iron Head':'Steel','Flash Cannon':'Steel','Bullet Punch':'Steel','Gigaton Hammer':'Steel',
  'Iron Defense':'Steel','Heavy Slam':'Steel','Body Press':'Fighting','King\'s Shield':'Steel',
  'Moonblast':'Fairy','Dazzling Gleam':'Fairy','Play Rough':'Fairy','Disarming Voice':'Fairy',
  'Light of Ruin':'Fairy','Draining Kiss':'Fairy','Calm Mind':'Psychic',
  'Rock Slide':'Rock','Stone Edge':'Rock','Rock Tomb':'Rock','Head Smash':'Rock',
  'Perish Song':'Normal','Parting Shot':'Dark','Life Dew':'Water','Recover':'Normal',
  'Synthesis':'Grass','Coil':'Poison','Nasty Plot':'Dark','Swords Dance':'Normal',
  'Bulk Up':'Fighting','Iron Defense':'Steel',
};

export function getPokemonImage(name) {
  if (!name) return '';
  const n = name.toLowerCase().trim();
  const overrides = {
    'mega gengar': 'gengar-mega','mega charizard y': 'charizard-megay',
    'mega charizard x': 'charizard-megax','mega blastoise': 'blastoise-mega',
    'mega venusaur': 'venusaur-mega','mega gardevoir': 'gardevoir-mega',
    'mega kangaskhan': 'kangaskhan-mega','mega froslass': 'froslass-mega',
    'mega aerodactyl': 'aerodactyl-mega','mega tyranitar': 'tyranitar-mega',
    'mega aggron': 'aggron-mega','mega camerupt': 'camerupt-mega',
    'mega lopunny': 'lopunny-mega','mega medicham': 'medicham-mega',
    'mega gallade': 'gallade-mega','mega altaria': 'altaria-mega',
    'mega salamence': 'salamence-mega','mega metagross': 'metagross-mega',
    'mega scizor': 'scizor-mega','mega heracross': 'heracross-mega',
    'mega alakazam': 'alakazam-mega','mega manectric': 'manectric-mega',
    'mega lucario': 'lucario-mega','mega blaziken': 'blaziken-mega',
    'mega ampharos': 'ampharos-mega','mega slowbro': 'slowbro-mega',
    'mega dragonite': 'dragonite-mega','mega scovillain': 'scovillain-mega',
    'mega meganium': 'meganium-mega','mega greninja': 'greninja-mega',
    'mega delphox': 'delphox-mega','mega golurk': 'golurk-mega',
    'mega floette': 'floette-mega','mega hawlucha': 'hawlucha-mega',
    'mega flygon': 'flygon-mega','mega goodra': 'goodra-mega',
    'mega gourgeist': 'gourgeist-mega',
    'zoroark-h': 'zoroark-hisui','hisui typhlosion': 'typhlosion-hisui',
    'ninetales-alola': 'ninetales-alola','wash-rotom': 'rotom-wash',
    'rotom-wash': 'rotom-wash','rotom-heat': 'rotom-heat','rotom-frost': 'rotom-frost',
    'charizard-y': 'charizard-megay','charizard y': 'charizard-megay',
  };
  const slug = overrides[n] || n.replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  return `https://play.pokemonshowdown.com/sprites/home/${slug}.png`;
}

// ── Full Meta DB — data from PokeSynergy (live) ──────────────────────────────
export const META_DB = {
  sneasler: {
    name:'Sneasler',types:['Fighting','Poison'],usage:43.8,wr:58.9,rank:1,tier:'LOVE',
    stats:{HP:80,Atk:130,Def:60,SpA:40,SpD:80,Spe:120},
    moves:[{m:'Close Combat',pct:100},{m:'Dire Claw',pct:97},{m:'Fake Out',pct:92},{m:'Protect',pct:75},{m:'Coaching',pct:12},{m:'Rock Tomb',pct:5}],
    items:[{i:'White Herb',pct:62},{i:'Focus Sash',pct:14},{i:'Life Orb',pct:8}],
    abilities:[{a:'Unburden',pct:95},{a:'Poison Touch',pct:5}],
    keyWarning:'LOVE TO SEE — Cannot Fake Out Ghosts. Close Combat = 0 to Ghost types. Only option is Dire Claw. Encore it and it is useless.',
  },
  garchomp: {
    name:'Garchomp',types:['Dragon','Ground'],usage:40.4,wr:59.3,rank:2,tier:'A',
    stats:{HP:108,Atk:130,Def:95,SpA:80,SpD:85,Spe:102},
    moves:[{m:'Earthquake',pct:91},{m:'Rock Slide',pct:82},{m:'Dragon Claw',pct:81},{m:'Protect',pct:71},{m:'Stomping Tantrum',pct:47},{m:'Swords Dance',pct:5}],
    items:[{i:'Choice Scarf',pct:18},{i:'Sitrus Berry',pct:14},{i:'Rocky Helmet',pct:9}],
    abilities:[{a:'Rough Skin',pct:88},{a:'Sand Veil',pct:12}],
    keyWarning:'18% Choice Scarf — scarfed Garchomp outspeeds everything. EQ hits both leads. Shuca Berry on Incineroar is critical. Disable Scarf = permanent lockout.',
  },
  incineroar: {
    name:'Incineroar',types:['Fire','Dark'],usage:35.84,wr:56.3,rank:3,tier:'B',
    stats:{HP:95,Atk:115,Def:90,SpA:80,SpD:90,Spe:60},
    moves:[{m:'Fake Out',pct:100},{m:'Parting Shot',pct:95},{m:'Flare Blitz',pct:89},{m:'Throat Chop',pct:41},{m:'Darkest Lariat',pct:39},{m:'Protect',pct:12}],
    items:[{i:'Sitrus Berry',pct:42},{i:'Chople Berry',pct:31},{i:'Shuca Berry',pct:12}],
    abilities:[{a:'Intimidate',pct:99}],
    keyWarning:'Dark type = Prankster Disable/Encore fail. 89% Flare Blitz. NEVER Parting Shot into Kingambit (Defiant). Mirror Fake Out: same speed tier, 50/50.',
  },
  kingambit: {
    name:'Kingambit',types:['Dark','Steel'],usage:38.21,wr:61.4,rank:4,tier:'S',
    stats:{HP:100,Atk:135,Def:120,SpA:60,SpD:85,Spe:50},
    moves:[{m:'Sucker Punch',pct:99},{m:'Kowtow Cleave',pct:88},{m:'Protect',pct:84},{m:'Iron Head',pct:55},{m:'Low Kick',pct:54},{m:'Swords Dance',pct:16}],
    items:[{i:'Black Glasses',pct:34},{i:'Chople Berry',pct:28},{i:'Focus Sash',pct:8}],
    abilities:[{a:'Defiant',pct:94},{a:'Supreme Overlord',pct:6}],
    keyWarning:'⚠ DEFIANT (94%) — NEVER Parting Shot or Intimidate. Sucker Punch priority threatens Gengar. Kommo-o Body Press ignores all Atk boosts.',
  },
  basculegion: {
    name:'Basculegion',types:['Water','Ghost'],usage:38.16,wr:60.8,rank:5,tier:'A',
    stats:{HP:120,Atk:112,Def:65,SpA:80,SpD:75,Spe:78},
    moves:[{m:'Last Respects',pct:99},{m:'Aqua Jet',pct:92},{m:'Wave Crash',pct:76},{m:'Flip Turn',pct:52},{m:'Protect',pct:48},{m:'Liquidation',pct:23}],
    items:[{i:'Choice Scarf',pct:44},{i:'Life Orb',pct:18},{i:'Mystic Water',pct:11}],
    abilities:[{a:'Swift Swim',pct:52},{a:'Adaptability',pct:48}],
    keyWarning:'⛔ GHOST — Escapes Shadow Tag. 44% Choice Scarf. Last Respects + each KO = more power. Shadow Ball immediately, never Perish Song.',
  },
  sinistcha: {
    name:'Sinistcha',types:['Grass','Ghost'],usage:26.87,wr:56.6,rank:6,tier:'A',
    stats:{HP:71,Atk:60,Def:106,SpA:121,SpD:80,Spe:70},
    moves:[{m:'Matcha Gotcha',pct:97},{m:'Rage Powder',pct:95},{m:'Trick Room',pct:70},{m:'Life Dew',pct:55},{m:'Protect',pct:40},{m:'Shadow Ball',pct:19}],
    items:[{i:'Covert Cloak',pct:38},{i:'Sitrus Berry',pct:29},{i:'Rocky Helmet',pct:16}],
    abilities:[{a:'Heatproof',pct:55},{a:'Water Absorb',pct:45}],
    keyWarning:'⛔ GHOST — Escapes Shadow Tag. Rage Powder redirects Body Press away from Kingambit. Shadow Ball immediately. 70% run Trick Room.',
  },
  'mega-floette': {
    name:'Mega Floette',types:['Fairy'],usage:21.37,wr:53.9,rank:7,tier:'B',
    stats:{HP:74,Atk:65,Def:67,SpA:125,SpD:128,Spe:92},
    moves:[{m:'Protect',pct:99},{m:'Dazzling Gleam',pct:96},{m:'Moonblast',pct:83},{m:'Calm Mind',pct:53},{m:'Light of Ruin',pct:45},{m:'Draining Kiss',pct:16}],
    items:[{i:'Life Orb',pct:38},{i:'Sitrus Berry',pct:28},{i:'Covert Cloak',pct:18}],
    abilities:[{a:'Flower Veil',pct:99}],
    keyWarning:'Lake2: "Love to see." Easy to Perish Song trap. Sableye Fake Out → set up PS. Gengar + Sableye both faster. Flower Veil prevents stat drops to Fairy allies.',
  },
  charizard: {
    name:'Mega Charizard Y',types:['Fire','Flying'],usage:17.86,wr:52.2,rank:8,tier:'A',
    stats:{HP:78,Atk:84,Def:78,SpA:109,SpD:85,Spe:100},
    moves:[{m:'Heat Wave',pct:99},{m:'Protect',pct:99},{m:'Solar Beam',pct:87},{m:'Weather Ball',pct:77},{m:'Air Slash',pct:12},{m:'Overheat',pct:12}],
    items:[{i:'Charizardite Y',pct:78},{i:'Life Orb',pct:14}],
    abilities:[{a:'Blaze',pct:82},{a:'Solar Power',pct:18}],
    keyWarning:'Cannot escape Shadow Tag — perfect Perish Song trap. Fake Out Charizard T1 + Gengar PS T2. Drought: Heat Wave destroys Sableye/Kommo-o. Smart players alternate moves to dodge Disable.',
  },
  pelipper: {
    name:'Pelipper',types:['Water','Flying'],usage:15.69,wr:51.0,rank:9,tier:'B',
    stats:{HP:60,Atk:50,Def:100,SpA:95,SpD:70,Spe:65},
    moves:[{m:'Hurricane',pct:98},{m:'Weather Ball',pct:87},{m:'Tailwind',pct:76},{m:'Protect',pct:51},{m:'Wide Guard',pct:44},{m:'Muddy Water',pct:12}],
    items:[{i:'Damp Rock',pct:52},{i:'Focus Sash',pct:28},{i:'Sitrus Berry',pct:12}],
    abilities:[{a:'Drizzle',pct:99}],
    keyWarning:'Rain setter — trap immediately, cannot escape Shadow Tag. Encore Weather Ball with no rain = Normal move that hits nothing. Stall rain turns with Protect.',
  },
  aerodactyl: {
    name:'Aerodactyl',types:['Rock','Flying'],usage:15.26,wr:50.2,rank:10,tier:'B',
    stats:{HP:80,Atk:105,Def:65,SpA:60,SpD:75,Spe:130},
    moves:[{m:'Rock Slide',pct:99},{m:'Tailwind',pct:98},{m:'Protect',pct:88},{m:'Dual Wingbeat',pct:84},{m:'Wide Guard',pct:21},{m:'Taunt',pct:4}],
    items:[{i:'Focus Sash',pct:44},{i:'Rocky Helmet',pct:22},{i:'Life Orb',pct:14}],
    abilities:[{a:'Rock Head',pct:52},{a:'Unnerve',pct:38},{a:'Pressure',pct:10}],
    keyWarning:'Speed tie with Gengar (base 130 vs 130). 98% Tailwind. 30% Rock Slide flinch. Fake Out it — Charizard next to it is usually the real threat.',
  },
  archaludon: {
    name:'Archaludon',types:['Steel','Dragon'],usage:13.81,wr:50.4,rank:11,tier:'B',
    stats:{HP:90,Atk:105,Def:130,SpA:125,SpD:65,Spe:116},
    moves:[{m:'Electro Shot',pct:92},{m:'Flash Cannon',pct:85},{m:'Protect',pct:84},{m:'Draco Meteor',pct:48},{m:'Dragon Pulse',pct:46},{m:'Aura Sphere',pct:24}],
    items:[{i:'Power Herb',pct:32},{i:'Assault Vest',pct:28},{i:'Life Orb',pct:18}],
    abilities:[{a:'Stamina',pct:54},{a:'Sturdy',pct:46}],
    keyWarning:'In Rain, Electro Shot charges instantly. 92% run it. Disable Electro Shot = permanent lockout. Almost always paired with Pelipper/Politoed.',
  },
  'rotom-wash': {
    name:'Rotom-Wash',types:['Electric','Water'],usage:13.46,wr:48.7,rank:12,tier:'A',
    stats:{HP:50,Atk:65,Def:107,SpA:105,SpD:107,Spe:86},
    moves:[{m:'Hydro Pump',pct:97},{m:'Thunderbolt',pct:74},{m:'Will-O-Wisp',pct:58},{m:'Protect',pct:54},{m:'Volt Switch',pct:53},{m:'Electroweb',pct:33}],
    items:[{i:'Sitrus Berry',pct:42},{i:'Iapapa Berry',pct:24},{i:'Rocky Helmet',pct:16}],
    abilities:[{a:'Levitate',pct:99}],
    keyWarning:'Volt Switch escapes Shadow Tag — Disable it immediately. Disabled Volt Switch = permanently locked by Shadow Tag since it can only use one move.',
  },
  farigiraf: {
    name:'Farigiraf',types:['Normal','Psychic'],usage:13.23,wr:47.6,rank:13,tier:'A',
    stats:{HP:120,Atk:90,Def:70,SpA:90,SpD:70,Spe:60},
    moves:[{m:'Trick Room',pct:97},{m:'Psychic',pct:66},{m:'Hyper Voice',pct:60},{m:'Helping Hand',pct:50},{m:'Protect',pct:46},{m:'Twin Beam',pct:17}],
    items:[{i:'Sitrus Berry',pct:42},{i:'Mental Herb',pct:22},{i:'Choice Specs',pct:14}],
    abilities:[{a:'Armor Tail',pct:78},{a:'Cud Chew',pct:22}],
    keyWarning:'Armor Tail blocks ALL Fake Out. Normal/Psychic = Ghost immune. Psychic SE into Gengar. Tinkaton Mold Breaker Fake Out bypasses Armor Tail. Target first.',
  },
  milotic: {
    name:'Milotic',types:['Water'],usage:10.83,wr:55.7,rank:14,tier:'C',
    stats:{HP:95,Atk:60,Def:79,SpA:100,SpD:125,Spe:81},
    moves:[{m:'Scald',pct:73},{m:'Protect',pct:69},{m:'Icy Wind',pct:55},{m:'Recover',pct:53},{m:'Muddy Water',pct:29},{m:'Coil',pct:28}],
    items:[{i:'Leftovers',pct:38},{i:'Sitrus Berry',pct:28},{i:'Rocky Helmet',pct:18}],
    abilities:[{a:'Marvel Scale',pct:72},{a:'Competitive',pct:28}],
    keyWarning:'28% run Competitive — NEVER Intimidate into Competitive Milotic. Icy Wind speed control is annoying but PS countdown ignores speed. Trap it easily.',
  },
  whimsicott: {
    name:'Whimsicott',types:['Grass','Fairy'],usage:10.64,wr:56.5,rank:15,tier:'B',
    stats:{HP:60,Atk:67,Def:85,SpA:77,SpD:75,Spe:116},
    moves:[{m:'Tailwind',pct:99},{m:'Moonblast',pct:92},{m:'Encore',pct:77},{m:'Protect',pct:53},{m:'Sunny Day',pct:32},{m:'Taunt',pct:10}],
    items:[{i:'Focus Sash',pct:38},{i:'Sitrus Berry',pct:28},{i:'Mental Herb',pct:18}],
    abilities:[{a:'Prankster',pct:94}],
    keyWarning:'Prankster Encore can lock your Protect loop — Disable it first. Cannot hit Gengar or Sableye with Moonblast (Fairy does nothing special). Fake Out it to cancel Tailwind.',
  },
  'mega-froslass': {
    name:'Mega Froslass',types:['Ice','Ghost'],usage:9.37,wr:50.8,rank:16,tier:'B',
    stats:{HP:70,Atk:80,Def:70,SpA:80,SpD:70,Spe:110},
    moves:[{m:'Blizzard',pct:100},{m:'Shadow Ball',pct:97},{m:'Protect',pct:97},{m:'Aurora Veil',pct:65},{m:'Substitute',pct:18},{m:'Nasty Plot',pct:8}],
    items:[{i:'Icy Rock',pct:38},{i:'Life Orb',pct:28},{i:'Covert Cloak',pct:18}],
    abilities:[{a:'Snow Warning',pct:99}],
    keyWarning:'⛔ GHOST — Escapes Shadow Tag. Lake2: "Love to see." Gengar outspeeds and 1HKOs with Shadow Ball. Snow Warning + Blizzard = 100% accuracy spread.',
  },
  aegislash: {
    name:'Aegislash',types:['Steel','Ghost'],usage:8.32,wr:50.8,rank:17,tier:'A',
    stats:{HP:60,Atk:50,Def:140,SpA:50,SpD:140,Spe:60},
    moves:[{m:"King's Shield",pct:91},{m:'Shadow Sneak',pct:76},{m:'Poltergeist',pct:73},{m:'Iron Head',pct:41},{m:'Close Combat',pct:26},{m:'Sacred Sword',pct:26}],
    items:[{i:'Weakness Policy',pct:38},{i:'Life Orb',pct:22},{i:'Lum Berry',pct:16}],
    abilities:[{a:'Stance Change',pct:99}],
    keyWarning:'⛔ GHOST — Escapes Shadow Tag. Shield form nearly undamageable. Shadow Sneak priority same bracket as Prankster — age decides. Better when in back 2.',
  },
  sylveon: {
    name:'Sylveon',types:['Fairy'],usage:8.01,wr:51.0,rank:18,tier:'C',
    stats:{HP:95,Atk:65,Def:65,SpA:110,SpD:130,Spe:60},
    moves:[{m:'Hyper Voice',pct:100},{m:'Quick Attack',pct:69},{m:'Protect',pct:58},{m:'Detect',pct:36},{m:'Moonblast',pct:33},{m:'Hyper Beam',pct:30}],
    items:[{i:'Choice Specs',pct:32},{i:'Sitrus Berry',pct:28},{i:'Life Orb',pct:18}],
    abilities:[{a:'Pixilate',pct:98}],
    keyWarning:'Hyper Voice spread — Kommo-o is immune (Soundproof). Gengar resists Fairy. Easy Perish Song trap. Disable Hyper Voice = it can do nothing meaningful.',
  },
  'mega-aerodactyl': {
    name:'Mega Aerodactyl',types:['Rock','Flying'],usage:7.94,wr:52.9,rank:19,tier:'B',
    stats:{HP:80,Atk:135,Def:85,SpA:70,SpD:95,Spe:150},
    moves:[{m:'Rock Slide',pct:99},{m:'Dual Wingbeat',pct:96},{m:'Tailwind',pct:86},{m:'Protect',pct:83},{m:'Wide Guard',pct:16},{m:'Ice Fang',pct:11}],
    items:[{i:'Focus Sash',pct:44},{i:'Life Orb',pct:22},{i:'Aerodactylite',pct:100}],
    abilities:[{a:'Tough Claws',pct:99}],
    keyWarning:'150 base speed — outspeeds Mega Gengar. Disable Tailwind or Rock Slide on T1. 86% Tailwind. Fake Out one then Disable the other.',
  },
  talonflame: {
    name:'Talonflame',types:['Fire','Flying'],usage:7.57,wr:59.4,rank:20,tier:'B',
    stats:{HP:78,Atk:81,Def:71,SpA:74,SpD:69,Spe:126},
    moves:[{m:'Tailwind',pct:100},{m:'Protect',pct:79},{m:'Flare Blitz',pct:48},{m:'Acrobatics',pct:38},{m:'Brave Bird',pct:29},{m:'Dual Wingbeat',pct:27}],
    items:[{i:'Life Orb',pct:38},{i:'Focus Sash',pct:28},{i:'Sitrus Berry',pct:18}],
    abilities:[{a:'Gale Wings',pct:94}],
    keyWarning:'Quick Guard blocks your Fake Out (breaks Gale Wings). Tailwind before PS is the concern. Incineroar resists both Fire and Flying. Fake Out Charizard (its partner) instead.',
  },
  'mega-tyranitar': {
    name:'Mega Tyranitar',types:['Rock','Dark'],usage:7.08,wr:49.5,rank:21,tier:'B',
    stats:{HP:100,Atk:134,Def:110,SpA:95,SpD:100,Spe:71},
    moves:[{m:'Rock Slide',pct:99},{m:'Protect',pct:98},{m:'Knock Off',pct:74},{m:'Low Kick',pct:52},{m:'Crunch',pct:23},{m:'Dragon Dance',pct:22}],
    items:[{i:'Tyranitarite',pct:100},{i:'Sitrus Berry',pct:32}],
    abilities:[{a:'Sand Stream',pct:99}],
    keyWarning:'Dark type — Prankster fails. Kommo-o Body Press 1HKOs (resists Rock/Dark). Gengar Shadow Ball cannot hit Dark types effectively. Kommo-o counters this perfectly.',
  },
  maushold: {
    name:'Maushold',types:['Normal'],usage:6.85,wr:46.6,rank:22,tier:'C',
    stats:{HP:74,Atk:75,Def:70,SpA:65,SpD:75,Spe:111},
    moves:[{m:'Follow Me',pct:98},{m:'Protect',pct:92},{m:'Super Fang',pct:79},{m:'Taunt',pct:31},{m:'Helping Hand',pct:25},{m:'Feint',pct:24}],
    items:[{i:'Sitrus Berry',pct:38},{i:'Focus Sash',pct:28},{i:'Covert Cloak',pct:18}],
    abilities:[{a:'Friend Guard',pct:72},{a:'Technician',pct:28}],
    keyWarning:'Follow Me redirects your Disable/Encore and Shadow Ball. Normal type = Ghost immune. Predictably uses Follow Me — Disable that first, then hit ally with Disable/Encore.',
  },
  'mega-delphox': {
    name:'Mega Delphox',types:['Fire','Psychic'],usage:6.51,wr:59.7,rank:23,tier:'S',
    stats:{HP:75,Atk:69,Def:72,SpA:114,SpD:100,Spe:130},
    moves:[{m:'Protect',pct:98},{m:'Heat Wave',pct:96},{m:'Psychic',pct:85},{m:'Encore',pct:34},{m:'Substitute',pct:32},{m:'Nasty Plot',pct:13}],
    items:[{i:'Life Orb',pct:38},{i:'Focus Sash',pct:28},{i:'Delphoxite',pct:100}],
    abilities:[{a:'Blaze',pct:82},{a:'Magician',pct:18}],
    keyWarning:'130 base speed — outspeeds Mega Gengar (130 base). Psychic 1HKO potential into Gengar. Sableye Prankster Disable fires first regardless of speed. Incineroar resists Psychic.',
  },
  'mega-gengar': {
    name:'Mega Gengar',types:['Ghost','Poison'],usage:6.47,wr:46.7,rank:24,tier:'CORE',
    stats:{HP:60,Atk:65,Def:80,SpA:170,SpD:95,Spe:130},
    moves:[{m:'Protect',pct:99},{m:'Shadow Ball',pct:97},{m:'Sludge Bomb',pct:66},{m:'Perish Song',pct:47},{m:'Disable',pct:35},{m:'Substitute',pct:20}],
    items:[{i:'Gengarite',pct:100}],
    abilities:[{a:'Shadow Tag',pct:100}],
    keyWarning:'Your core. 47% run Perish Song, 35% Disable, 20% Substitute. Shadow Tag = nothing escapes unless Ghost type.',
  },
  corviknight: {
    name:'Corviknight',types:['Steel','Flying'],usage:5.93,wr:55.2,rank:25,tier:'C',
    stats:{HP:98,Atk:87,Def:105,SpA:53,SpD:85,Spe:67},
    moves:[{m:'Brave Bird',pct:79},{m:'Roost',pct:62},{m:'Tailwind',pct:61},{m:'Body Press',pct:55},{m:'Iron Head',pct:48},{m:'Bulk Up',pct:39}],
    items:[{i:'Sitrus Berry',pct:38},{i:'Leftovers',pct:28},{i:'Rocky Helmet',pct:18}],
    abilities:[{a:'Mirror Armor',pct:72},{a:'Pressure',pct:28}],
    keyWarning:'Mirror Armor reflects stat drops — Intimidate bounces back! NEVER Intimidate into Corviknight. Tailwind setter. Perish Song trap it easily.',
  },
  'mega-dragonite': {
    name:'Mega Dragonite',types:['Dragon','Flying'],usage:5.52,wr:53.1,rank:26,tier:'B',
    stats:{HP:91,Atk:154,Def:95,SpA:100,SpD:100,Spe:80},
    moves:[{m:'Hurricane',pct:86},{m:'Protect',pct:72},{m:'Draco Meteor',pct:51},{m:'Dragon Pulse',pct:43},{m:'Tailwind',pct:33},{m:'Thunder',pct:28}],
    items:[{i:'Dragonite',pct:100},{i:'Life Orb',pct:18}],
    abilities:[{a:'Multiscale',pct:78},{a:'Inner Focus',pct:22}],
    keyWarning:'Multiscale halves damage at full HP — takes 3 turns to KO anyway, so Perish Song trap is ideal. Gengar outspeeds. Disable Hurricane if in Rain.',
  },
  kommo_o: {
    name:'Kommo-o',types:['Dragon','Fighting'],usage:4.38,wr:60.0,rank:27,tier:'CORE',
    stats:{HP:75,Atk:110,Def:125,SpA:100,SpD:105,Spe:85},
    moves:[{m:'Protect',pct:98},{m:'Clanging Scales',pct:91},{m:'Aura Sphere',pct:83},{m:'Clangorous Soul',pct:83},{m:'Body Press',pct:8},{m:'Iron Defense',pct:7}],
    items:[{i:'Throat Spray',pct:52},{i:'Lum Berry',pct:28},{i:'Sitrus Berry',pct:18}],
    abilities:[{a:'Soundproof',pct:88},{a:'Bulletproof',pct:12}],
    keyWarning:'Opponent Kommo-o: Soundproof = IMMUNE to Perish Song. Cannot trap it. Primarina Moonblast 1HKOs. If you see opponent Kommo-o, bring Primarina.',
  },
  primarina: {
    name:'Primarina',types:['Water','Fairy'],usage:4.34,wr:55.8,rank:28,tier:'CORE',
    stats:{HP:80,Atk:74,Def:74,SpA:126,SpD:116,Spe:60},
    moves:[{m:'Moonblast',pct:88},{m:'Perish Song',pct:72},{m:'Protect',pct:68},{m:'Flip Turn',pct:58},{m:'Sparkling Aria',pct:22},{m:'Icy Wind',pct:15}],
    items:[{i:'Sitrus Berry',pct:42},{i:'Assault Vest',pct:22},{i:'Throat Pearl',pct:18}],
    abilities:[{a:'Torrent',pct:82},{a:'Liquid Voice',pct:18}],
    keyWarning:'72% run Perish Song on opponents too. Resists Dragon + Dark (Hydreigon counter). Moonblast 1HKOs opponent Kommo-o. Low speed = Flip Turn fires last.',
  },
  hatterene: {
    name:'Hatterene',types:['Psychic','Fairy'],usage:4.2,wr:54.2,rank:29,tier:'A',
    stats:{HP:57,Atk:90,Def:95,SpA:136,SpD:103,Spe:29},
    moves:[{m:'Trick Room',pct:97},{m:'Psychic',pct:82},{m:'Mystical Fire',pct:58},{m:'Protect',pct:48},{m:'Dazzling Gleam',pct:32}],
    items:[{i:'Life Orb',pct:42},{i:'Focus Sash',pct:28},{i:'Covert Cloak',pct:18}],
    abilities:[{a:'Magic Bounce',pct:92}],
    keyWarning:'Magic Bounce reflects Encore AND Disable — Prankster or not. Slowest in meta = TR anchor. ONLY Tinkaton Mold Breaker can Encore/Fake Out it normally.',
  },
  froslass: {
    name:'Mega Froslass',types:['Ice','Ghost'],usage:9.37,wr:50.8,rank:16,tier:'B',
    stats:{HP:70,Atk:80,Def:70,SpA:80,SpD:70,Spe:110},
    moves:[{m:'Blizzard',pct:100},{m:'Shadow Ball',pct:97},{m:'Protect',pct:97},{m:'Aurora Veil',pct:65}],
    items:[{i:'Icy Rock',pct:38},{i:'Life Orb',pct:28}],
    abilities:[{a:'Snow Warning',pct:99}],
    keyWarning:'⛔ GHOST — Escapes Shadow Tag. Gengar outspeeds and Shadow Ball 1HKOs.',
  },
};

// ── Lead frequency data ───────────────────────────────────────────────────────
export const COMMON_LEADS = {
  sneasler:    {partners:['Garchomp','Aerodactyl','Charizard','Sinistcha'],pct:72},
  garchomp:    {partners:['Sneasler','Charizard','Aerodactyl','Kingambit'],pct:65},
  charizard:   {partners:['Garchomp','Aerodactyl','Sneasler','Talonflame'],pct:70},
  aerodactyl:  {partners:['Sneasler','Garchomp','Charizard','Kingambit'],pct:74},
  pelipper:    {partners:['Archaludon','Basculegion','Sneasler','Kingambit'],pct:80},
  farigiraf:   {partners:['Camerupt','Kangaskhan','Hatterene','Blastoise'],pct:84},
  hatterene:   {partners:['Camerupt','Farigiraf','Kangaskhan','Golurk'],pct:70},
  whimsicott:  {partners:['Charizard','Garchomp','Sneasler','Kingambit'],pct:64},
  sinistcha:   {partners:['Sneasler','Kingambit','Garchomp','Basculegion'],pct:60},
  archaludon:  {partners:['Pelipper','Politoed','Sneasler','Kingambit'],pct:76},
  talonflame:  {partners:['Charizard','Garchomp','Sneasler','Torkoal'],pct:66},
  maushold:    {partners:['Kingambit','Garchomp','Sneasler','Basculegion'],pct:62},
  whimsicott:  {partners:['Charizard','Sneasler','Garchomp','Kingambit'],pct:64},
};

// ── Speed tier data (Champions formula: (base + SP + 20) × nature) ───────────
// Formula verified: Sneasler Jolly 32SP = 189, Gengar Timid 8SP = 151, Incin Impish 2SP = 82
export function calcSpeed(base, sp, nature) {
  const mult = nature === '+' ? 1.1 : nature === '-' ? 0.9 : 1.0;
  return Math.floor((base + sp + 20) * mult);
}

export const SPEED_TIERS = [
  // name, baseSpe, label, tier color, isMyMon
  {name:'Meowscarada',     base:123, nature:'+', sp:32, clr:'#E050E0', note:'Top threat — very fast, rarely leads in this meta'},
  {name:'Dragapult',       base:142, nature:'+', sp:32, clr:'#FF4444', isGhost:true, note:'⛔ Ghost — escapes trap. Outspeeds Gengar. Shadow Ball immediately'},
  {name:'Greninja',        base:122, nature:'+', sp:32, clr:'#8888CC', note:'Mega Greninja: Water/Dark — Prankster fails'},
  {name:'Sneasler',        base:120, nature:'+', sp:32, clr:'#5DCAA5', note:'LOVE TO SEE — cannot touch Sableye/Gengar'},
  {name:'Mega Aerodactyl', base:150, nature:'+', sp:32, clr:'#EF9F27', note:'Outspeeds Gengar — faster than base Aerodactyl'},
  {name:'Mega Delphox',    base:130, nature:'+', sp:32, clr:'#FF4444', note:'Outspeeds Gengar — Psychic 1HKO threat. Disable via Sableye'},
  {name:'Aerodactyl',      base:130, nature:'+', sp:32, clr:'#EF9F27', note:'Speed tie with base Mega Gengar — 50/50 unless you invest'},
  {name:'Gengar (battle)', base:130, nature:'+', sp:8,  clr:'#AFA9EC', isMyMon:true, note:'Your Mega Gengar in battle — 173 battle speed'},
  {name:'Talonflame',      base:126, nature:'+', sp:32, clr:'#F0997B', note:'Quick Guard blocks Fake Out. Tailwind setter'},
  {name:'Whimsicott',      base:116, nature:'+', sp:32, clr:'#97C459', note:'Prankster Encore can lock your Protect loop'},
  {name:'Archaludon',      base:116, nature:'+', sp:32, clr:'#85B7EB', note:'Fast for Steel/Dragon — Electro Shot in rain is instant'},
  {name:'Mega Froslass',   base:110, nature:'+', sp:32, clr:'#88CCDD', isGhost:true, note:'⛔ Ghost — Shadow Ball KOs. Gengar outspeeds'},
  {name:'Tinkaton',        base:110, nature:'+', sp:27, clr:'#85B7EB', isMyMon:true, note:'Your Tinkaton — 155 speed'},
  {name:'Maushold',        base:111, nature:'+', sp:32, clr:'#B4B2A9', note:'Follow Me redirector — Disable Follow Me first'},
  {name:'Meowscarada (−)', base:123, nature:'0', sp:32, clr:'#B080C0', note:'Neutral nature — still very fast'},
  {name:'Mega Scizor',     base:75,  nature:'+', sp:32, clr:'#CC4444', note:'Bullet Punch priority — Swords Dance variant threat'},
  {name:'Rotom-Wash',      base:86,  nature:'+', sp:32, clr:'#5580DD', note:'Volt Switch escapes Shadow Tag — Disable it'},
  {name:'Milotic',         base:81,  nature:'+', sp:32, clr:'#88BBDD', note:'28% Competitive — NEVER Intimidate this'},
  {name:'Primarina',       base:60,  nature:'0', sp:3,  clr:'#ED93B1', isMyMon:true, note:'Your Primarina — slow intentionally for Flip Turn loop'},
  {name:'Incineroar',      base:60,  nature:'0', sp:2,  clr:'#F0997B', isMyMon:true, note:'Your Incineroar — slow Parting Shot fires late (safe Gengar entry)'},
  {name:'Sableye',         base:50,  nature:'0', sp:0,  clr:'#B4B2A9', isMyMon:true, note:'Your Sableye — Prankster makes speed irrelevant for priority moves'},
  {name:'Kommo-o (opp)',   base:85,  nature:'+', sp:32, clr:'#5DCAA5', note:'Opponent Kommo-o — Soundproof, immune to Perish Song'},
  {name:'Kommo-o',         base:85,  nature:'0', sp:0,  clr:'#5DCAA5', isMyMon:true, note:'Your Kommo-o — 105 speed. Safe PS-immune switch'},
  {name:'Farigiraf',       base:60,  nature:'0', sp:0,  clr:'#EF9F27', note:'TR setter — Armor Tail blocks Fake Out. Tinkaton counters'},
  {name:'Kingambit',       base:50,  nature:'0', sp:0,  clr:'#FF4444', note:'Defiant — slow but Sucker Punch is priority. Never PS/Intimidate'},
  {name:'Hatterene',       base:29,  nature:'-', sp:0,  clr:'#C8A2E8', note:'Slowest in meta — TR anchor. Tinkaton Mold Breaker counters'},
];

// ── Scarf speed multiplier = 1.5 ──────────────────────────────────────────────
export const SCARF_MULTIPLIER = 1.5;
